#!/usr/bin/env bash
#
# Persistent isolated DSH instance for end-to-end checks.
#
# Why: verifying a plugin change must not touch the instance you are working in
# (`HOME` + `DSH_HOME` both isolated), and rebuilding that instance by hand every
# time is wasteful. This keeps ONE isolated home around and reuses it:
#
#   scripts/e2e-isolated-home.sh setup        # create/refresh the home + profile (idempotent)
#   scripts/e2e-isolated-home.sh key-link     # print the ONE line YOU run to lend the model key
#   scripts/e2e-isolated-home.sh doctor       # preflight: config, plugin row, key present?
#   scripts/e2e-isolated-home.sh launch -- --port 3311 --no-open
#   scripts/e2e-isolated-home.sh reset        # drop sessions + audit trail, keep the home
#
# The key: the isolated home needs a model route, and the plugin's own hard floor
# refuses to let an agent read or copy key material — even when the user asks
# (that is the design; it was enforced against its own author, twice). So the ONE
# step this script cannot do is the credential link: it PRINTS the line for YOU
# to run outside auto mode. Everything after that is self-service.
#
# Env knobs: DSH_E2E_HOME (default ~/.dsh-e2e), DSH_E2E_PROFILE (e2e),
#            DSH_E2E_CLONE_FROM (web), DSH_E2E_PROVIDER (deepseek-official),
#            DSH_E2E_MODEL (deepseek-flash), DSH_CLI (path to the dsh entrypoint).
set -euo pipefail

ROOT="${DSH_E2E_HOME:-$HOME/.dsh-e2e}"
PROFILE="${DSH_E2E_PROFILE:-e2e}"
CLONE_FROM="${DSH_E2E_CLONE_FROM:-web}"
PROVIDER="${DSH_E2E_PROVIDER:-opencode-go-chat}"
MODEL="${DSH_E2E_MODEL:-space-bunny-free}"
PLUGIN_PKG="${DSH_E2E_PLUGIN_PKG:-@log.li/dsh-automode}"
PLUGIN_DIR="${DSH_E2E_PLUGIN_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
HOME_DIR="$ROOT/home"
DSH_HOME_DIR="$HOME_DIR/.dsh"
PROFILE_DIR="$DSH_HOME_DIR/profiles/$PROFILE"

say() { printf '%s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# A test home must never live inside the repo: it holds sessions, audit trails and
# (once linked) the model key, none of which may ever reach git. Fail closed even
# if someone points DSH_E2E_HOME there.
guard_outside_repo() {
  local repo_root
  repo_root="$(git -C "$PLUGIN_DIR" rev-parse --show-toplevel 2>/dev/null || true)"
  [[ -n "$repo_root" ]] || return 0
  case "$ROOT" in
    "$repo_root"|"$repo_root"/*)
      die "DSH_E2E_HOME ($ROOT) is inside the repository ($repo_root) — keep test homes outside it so git can never see sessions or key links"
      ;;
  esac
}
guard_outside_repo

find_cli() {
  if [[ -n "${DSH_CLI:-}" ]]; then printf '%s' "$DSH_CLI"; return; fi
  local c
  for c in "$HOME/.npm-global/lib/node_modules/@deepseek-ai/dsh/lib/bin.js" \
           "/opt/homebrew/lib/node_modules/@deepseek-ai/dsh/lib/bin.js" \
           "/usr/local/lib/node_modules/@deepseek-ai/dsh/lib/bin.js"; do
    [[ -f "$c" ]] && { printf '%s' "$c"; return; }
  done
  return 1
}

node_bin() {
  local n; n="$(command -v node 2>/dev/null || true)"
  [[ -n "$n" ]] || n="/opt/homebrew/bin/node"
  [[ -x "$n" ]] || die "no node found"
  printf '%s' "$n"
}

# The cloned profile carries RELATIVE plugin symlinks that resolve against the
# ORIGINAL home (five levels up). Recreating that shape inside the isolated home
# keeps them working without rewriting each link.
link_plugin_shortcuts() {
  mkdir -p "$HOME_DIR/Projects"
  local repo
  for repo in "$(dirname "$PLUGIN_DIR")"/*; do
    [[ -d "$repo" ]] || continue
    ln -sfn "$repo" "$HOME_DIR/Projects/$(basename "$repo")"
  done
}

cmd_setup() {
  [[ -d "$HOME/.dsh/profiles/$CLONE_FROM" ]] || die "no profile '$CLONE_FROM' to clone from"
  mkdir -p "$DSH_HOME_DIR/profiles"
  if [[ ! -d "$PROFILE_DIR" ]]; then
    say "cloning profile '$CLONE_FROM' → '$PROFILE' (APFS clonefile)"
    cp -Rc "$HOME/.dsh/profiles/$CLONE_FROM" "$PROFILE_DIR"
  else
    say "profile '$PROFILE' already exists — keeping it (use DSH_E2E_PROFILE to make another)"
  fi
  link_plugin_shortcuts

  cat > "$PROFILE_DIR/package.json" <<JSON
{
  "name": "dsh-profile-$PROFILE",
  "private": true,
  "dsh": {
    "profile": {
      "bundles": [
        "@deepseek-ai/dsh-base",
        "@deepseek-ai/dsh-web-app",
        "$PLUGIN_PKG"
      ]
    }
  }
}
JSON

  cat > "$PROFILE_DIR/cordis.patch.yml" <<YAML
# Isolated E2E profile — generated by scripts/e2e-isolated-home.sh.
# Throwaway values only: no user config, no secrets (the route key is symlinked
# in by the human, see \`key-link\`).
- id: llm-pi-ai
  name: "@deepseek-ai/dsh-llm-pi-ai"
  config:
    providers:
      opencode-go-chat:
        apiKeyEnv: OPENCODE_GO_API_KEY
        api: openai-completions
        baseURL: https://opencode.ai/zen/go/v1
        headers:
          x-opencode-session: dsh-e2e
        models:
          - id: space-bunny-free
            name: Space Bunny Free
            contextWindow: 1048576
            maxTokens: 131072
            compat:
              supportsStore: false
              supportsDeveloperRole: false
              maxTokensField: max_tokens
          - id: glm-5.3-flash
            name: GLM 5.3 Flash
            contextWindow: 1000000
            maxTokens: 128000
      opencode-go:
        apiKeyEnv: OPENCODE_GO_API_KEY
        api: openai-responses
        baseURL: https://opencode.ai/zen/go/v1
        headers:
          x-opencode-session: dsh-e2e
        models:
          - id: deepseek-flash
            name: DeepSeek Flash
            contextWindow: 1000000
            maxTokens: 384000

- id: agent-default-model
  name: "@deepseek-ai/dsh-agent-default-model"
  config:
    provider: $PROVIDER
    model: $MODEL

# Kept as a second route: it reads its own ref, so whichever key is lent to this
# home decides which route works (a route with no key fails with MISSING_CREDENTIAL).
- id: llm-deepseek
  name: "@deepseek-ai/dsh-llm-deepseek-api-key"
  config:
    models:
      - id: deepseek-flash
        name: DeepSeek-V41-Flash
        contextWindow: 1000000
        systemPromptUpdate: in-history

- id: auto-mode
  config:
    allowPaths:
      - '/tmp/'
YAML

  # Always mount the driver: with E2E_PROMPT unset it records "idle" and does
  # nothing, and keeping it unconditional means re-running `setup` can never
  # silently drop it (which it did once — the profile patch is rewritten whole).
  ln -sfn "$PLUGIN_DIR/scripts/e2e-drive" "$PROFILE_DIR/node_modules/dsh-e2e-drive"
  cat >> "$PROFILE_DIR/cordis.patch.yml" <<'YAML'

- insert:
    - id: e2e-drive
      name: dsh-e2e-drive
YAML
  say "driver mounted: dsh-e2e-drive (inert until E2E_PROMPT is set)"
  say "wrote $PROFILE_DIR/{package.json,cordis.patch.yml} (plugin: $PLUGIN_DIR)"
  cmd_key_link
}

cmd_key_link() {
  cat <<EOF

ONE manual step (you, outside auto mode) — lend this throwaway home the model key:

  mkdir -p "$DSH_HOME_DIR" && ln -sfn "$HOME/.dsh/.credentials.yaml" "$DSH_HOME_DIR/.credentials.yaml"

Why you and not the agent: reading or copying key material is on the plugin's hard
floor, so the gate refuses it even when the user authorizes it. A symlink is used
on purpose — nothing is duplicated, the store stays 0600, and \`reset\` cannot
delete your real key.

EOF
}

cmd_doctor() {
  local cli node ok=0
  cli="$(find_cli)" || die "cannot find the dsh CLI (set DSH_CLI)"
  node="$(node_bin)"
  say "home:    $HOME_DIR"
  say "DSH_HOME:$DSH_HOME_DIR"
  say "profile: $PROFILE"
  say "cli:     $cli"
  local repo_root
  repo_root="$(git -C "$PLUGIN_DIR" rev-parse --show-toplevel 2>/dev/null || true)"
  if [[ -n "$repo_root" && "$ROOT" == "$repo_root"* ]]; then
    say "git:     INSIDE the repo — refused"; ok=1
  else
    say "git:     outside ${repo_root:-the repo} ✓ (git can never see this home)"
  fi

  if [[ -e "$DSH_HOME_DIR/.credentials.yaml" ]]; then
    say "key:     present ($(readlink "$DSH_HOME_DIR/.credentials.yaml" 2>/dev/null || echo 'real file'))"
  else
    say "key:     MISSING — run: $0 key-link"; ok=1
  fi
  if [[ -d "$PROFILE_DIR/node_modules/$PLUGIN_PKG" || -e "$PROFILE_DIR/node_modules/$PLUGIN_PKG" ]]; then
    say "plugin:  resolvable via profile node_modules"
  else
    say "plugin:  NOT resolvable — does the profile link $PLUGIN_PKG?"; ok=1
  fi
  if HOME="$HOME_DIR" DSH_HOME="$DSH_HOME_DIR" "$node" "$cli" --profile "$PROFILE" --dump-config 2>/dev/null | grep -q -- "- id: auto-mode"; then
    say "config:  - id: auto-mode present"
  else
    say "config:  auto-mode row NOT in the composed tree"; ok=1
  fi
  return $ok
}

cmd_launch() {
  local cli node
  cli="$(find_cli)" || die "cannot find the dsh CLI (set DSH_CLI)"
  node="$(node_bin)"
  # The driver must be told the route explicitly: a programmatically created
  # agent does not inherit the profile's `agent-default-model` row.
  export E2E_PROVIDER="${E2E_PROVIDER:-$PROVIDER}"
  export E2E_MODEL="${E2E_MODEL:-$MODEL}"
  HOME="$HOME_DIR" DSH_HOME="$DSH_HOME_DIR" exec "$node" "$cli" --profile "$PROFILE" "$@"
}

cmd_reset() {
  local trash="$HOME/bin/trash"
  local victims=("$DSH_HOME_DIR/sessions" "$DSH_HOME_DIR/auto-mode")
  local v
  for v in "${victims[@]}"; do
    [[ -e "$v" ]] || continue
    if [[ -x "$trash" ]]; then "$trash" "$v" >/dev/null; else mv "$v" "$v.reset.$(date +%s)"; fi
    say "cleared $(basename "$v")"
  done
}

# Materialize a PREVIOUS release's lib/ for red controls: the driver feeds the
# same live messages to it and to the working tree, so "the old one could not see
# this" is reproducible. Needs a node_modules next to it (bare imports), which a
# symlink to the repo's own install provides.
cmd_seed_oldlib() {
  local ref="${1:-}"
  if [[ -z "$ref" ]]; then
    # Default to the release BEFORE the newest one — that is the "red" side of a
    # red/green control for whatever is being fixed here.
    local latest
    latest="$(git -C "$PLUGIN_DIR" describe --tags --abbrev=0 HEAD 2>/dev/null || true)"
    if [[ -n "$latest" ]]; then
      ref="$(git -C "$PLUGIN_DIR" describe --tags --abbrev=0 "${latest}^" 2>/dev/null || true)"
    fi
  fi
  [[ -n "$ref" ]] || die "usage: $0 seed-oldlib <git-ref>"
  local dest="$ROOT/oldlib"
  if [[ -e "$dest" ]]; then
    if [[ -x "$HOME/bin/trash" ]]; then "$HOME/bin/trash" "$dest" >/dev/null; else mv "$dest" "$dest.$(date +%s)"; fi
  fi
  mkdir -p "$dest"
  git -C "$PLUGIN_DIR" archive "$ref" lib | tar -x -C "$dest"
  ln -sfn "$PLUGIN_DIR/node_modules" "$dest/node_modules"
  say "seeded $ref → $dest/lib"
  say "use: E2E_OLD_LIB=$dest/lib"
}

case "${1:-}" in
  setup)
    shift
    for arg in "$@"; do
      case "$arg" in
        --with-driver) WITH_DRIVER=1 ;;
        *) die "unknown setup flag: $arg" ;;
      esac
    done
    cmd_setup
    ;;
  key-link) shift; cmd_key_link "$@" ;;
  doctor)   shift; cmd_doctor "$@" ;;
  launch)   shift; [[ "${1:-}" == "--" ]] && shift; cmd_launch "$@" ;;
  reset)    shift; cmd_reset "$@" ;;
  seed-oldlib) shift; cmd_seed_oldlib "$@" ;;
  *) sed -n '3,20p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//' ; exit 2 ;;
esac
